Fix Travis deployment

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,41 +20,60 @@ env:
   - PYTHON_DEBUG=1
   - WINEDEBUG=fixme-all
   matrix:
-  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="" CHECK_DOC=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
-  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
-  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="" GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash"
-  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
-  - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq" DEP_OPTS="DEBUG=1" GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER"
-  - HOST=x86_64-unknown-linux-gnu PACKAGES="python3" GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
-  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"
+  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="" CHECK_DOC=1
+    GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
+  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="" PACKAGES="python3 nsis
+    g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
+  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="" GOAL="install"
+    BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports
+    LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash"
+  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="" PACKAGES="python3 nsis
+    g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
+  - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq" DEP_OPTS="DEBUG=1" GOAL="install"
+    BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports
+    CPPFLAGS=-DDEBUG_LOCKORDER"
+  - HOST=x86_64-unknown-linux-gnu PACKAGES="python3" GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat
+    --enable-reduce-exports"
+  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
+    libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports"
+    OSX_SDK=10.11 GOAL="deploy"
 before_install:
-- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
+  sed "s|::|:|g")
 install:
 - if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
-- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
+- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
+  fi
 - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
+  --no-upgrade -qq $PACKAGES; fi
 before_script:
 - unset CC; unset CXX
 - if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
 - mkdir -p depends/SDKs depends/sdk-sources
-- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
+  fi
+- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
 - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
 script:
 - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
 - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
 - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
+- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
+  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
 - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
 - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
 - mkdir build && cd build
 - "../configure $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)"
-- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
+- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
+  V=1 ; false )
 - if [ -n "$OSX_SDK" ]; then cd .. ; fi
 - if [ -n "$OSX_SDK" ]; then mkdir out; fi
 - if [ -n "$OSX_SDK" ]; then mkdir out/$TRAVIS_PULL_REQUEST; fi
-- if [ -n "$OSX_SDK" ]; then mkdir out/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST; fi
+- if [ -n "$OSX_SDK" ]; then mkdir out/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST;
+  fi
 - if [ -n "$OSX_SDK" ]; then mkdir ${OUTDIR}/bin; fi
 - if [ -n "$OSX_SDK" ]; then cp -rf build/Vertcoin-Qt.app ${OUTDIR}/bin; fi
 - if [ -n "$OSX_SDK" ]; then cp -rf build/Vertcoin-Core.dmg ${OUTDIR}/bin; fi
@@ -66,13 +85,12 @@ after_script:
 - echo $TRAVIS_COMMIT_LOG
 notifications:
   irc: chat.freenode.net#multicoin-co
-before_deploy: cd ${OUTDIR}/../ && tar -zcvf vertcoin-$HOST.tar.gz ${OUTDIR}
+before_deploy: cd ${OUTDIR}/../ && zip -r vertcoin-$HOST.zip ${OUTDIR}
 deploy:
   skip_cleanup: true
   provider: releases
   api_key:
-    secure: qIy6+q/eTBobBUuA/Mat9n86cDBwaGn7FgQYzBUjNVGJLyT5k3DRyH8ZcKCHkI+Xbnhnc6sZxlFfyFyz/XMAGD6fubT0tOlPmmXaWhjf/g8KGiFS/n6hj6hzL2XGgIrbw1vb89q8ORuNmcG6i1ks9Ev/LhVQ1X9zhnRctyo6BUovpYO5HuG7rtlkDdg/fMBLISXmFFkD/3y37Te+oyTq+FR/gMepxg75zW4kkVsA5jP816OVlctLEDs84K9N0Aqe60vY4oCCKzYSkLqxsN1SVI7B+skeP/dFoBakqmjxL/3JOK2HVv7HyXXkSW8NjmIDAIBNW1OFiVUVk5h0a/iGPjN58b2EIUWvM75F18KelLAzif+Ovu510PyoF6aDxF16RymlokP3j2l3QeQTc7NiLCqzzGAgR+HNSziKdBZPZfpGzLNk/1Kk5l/uUjVM2x4ehq0nvddKz9v/nEiRbvPYu0lZyL61QcGmf0ZYGMOkLczs5R2ddNfUaUKknw2Oy5ZydBfWaP+SPLmz/OpTDHKaDkYuCUJ9caO7srQYCN6qkUfRGTq+UJ67IrXbVQpdSe0rwKQKpXUtlTG3YBwlToasvDbzagrF/UJha2cGLq90y44BaHr6bQjgokw8NXSKrrHkh0mPoBW8MWpKqm2n356YDLktPyvTq6CsEiZsfZxT7vg=
-  file:
-    - ${OUTDIR}/..//vertcoin-$HOST.tar.gz
+    secure: fnes0KZvtingUXqcn2NIDPnUV75nOwIgnjvz5GaT4V2uE4dtioYdG12+TVLPqdtL81ulfh2LS8QPzozoGMZnt/Ywnz6LJLdVWSLx7fmZehgo8IAgsMR3RQlkO6QQ4kUbZwDW3Lno908mGawu6p0u2FSpZ0ZSUFm/zy4mEU50R7BlD10LF1L/0Q71GROouS5ekBsGdS2fomah98OmGgVR7SxvUt1CW7l5VxILLahP/O+xJdo0EmWOs89ajpvc6xAXgZJBNB/A+djdv/IuTAlvMS3iTdgkkN6l2mF0Ibs11ZMqJlRrH3T+p3OrLIFTdJJ0ACEOwbmmAZLmp9jcT8ac4LXrpkH3FZUPh+YGBWmbBBBh9db/IjxCEWM19KYawkWxAwEsfJfcbN2DWtPCZjjsGY6Y+KMEQ2sUDr8K7chOXYYTe91fDcGHE42K5gVOCfpj2afYWjUjgHAzy+Gq3FNiTAJQFzRds2mAblMlJrt7Yf2nN6LJmNJfXwVsIBNF//Pey8zpVn+aq4l4iylDkGrb0eAehxPUElBDwg6zIGseniZoyECbGuZ2IVm7SXLgCbfs7MXQ5koYDfpXiNJKsDkIl52NTe73+LlYZa6dGYzCjN2Kr0+j8U7sWYkSOe36CNeytFm6Qpjlsxsno8Vr3pQ9hGYkDUGWRISnbL2L1FooB0o=
+  file: "${OUTDIR}/..//vertcoin-$HOST.zip"
   on:
-    repo: ahmedbodi/vertcoin
+    repo: vertcoin/vertcoin-1
